import type { Metadata } from 'next'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navigation } from './components/navigation/Navigation'
import { NavigationStatus } from './components/navigationStatus/NavigationStatus'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover"
        />
        <meta name="theme-color" content="#072141" />
      </Head>
      <body className={inter.className}>
        <Navigation />
        {children}
        <NavigationStatus />
      </body>
    </html>
  )
}
